### ISSUE TITLE
sb - se, sc - sf 

### ISSUE THREAD

**Issue by FlyingEagle** [bunnyhu/ESP8266_TX20_wind_sensor#1]
Which one of the variables above is the right for the real wind-speed and the real wind-direction?

**Comment by bunnyhu** [comment]
sprintf(a, "Wind direction: %d\t%d\n", sb, se);
sprintf(a, "Wind speed: %d\t%d\n", sc, sf);

Both is real :) You can dig the code in my weather station, also here in github.
https://github.com/bunnyhu/wemos_d1_mini_weatherstation
