### ISSUE TITLE
Crash when using Wifi

### ISSUE THREAD

**Issue by acfischer42** [bunnyhu/ESP8266_TX20_wind_sensor#2]
Thanks a lot for the code. Base code with decoding is working nicely.
I had an issue on my setup though that my ESP8266 kept crashing after download and seemed to not work. I found out that this was due to conflict with Wifi.

Solution:
ICACHE_RAM_ATTR void isTX20Rising() 
instead of void isTX20Rising() 

(And not use pin D4) - not in your code, but in my test setup and not working.

**Comment by bunnyhu** [comment]
Thanks for the solution! I had no this kind of problem when I made the code, but my weather station is running without any change like 8 years 7/24. Maybe the ESP microcode is updated since that.
